---
title: "Пример статистического анализа"
author: "Anastasia Soroka"
date: "2023-08-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(readr)
library(dplyr)
library(psych)
library(ggplot2)

library(tibble)
```
# Импорт данных
Данные, используемые в этом проекте - данные по группе крови и показателям крови двух групп пациентов.

```{r data import}

data_1 <- read_tsv("Data/data_tsv.tsv", show_col_types = FALSE)
head(data_1)

```
# Базовые статистики

## Data summary
```{r}
# Data summary
data_info_1 <- summary(data_1)
data_info_1
```

## Data describe
```{r}
data_info_2 <- describe(data_1, na.rm = TRUE, skew = FALSE, ranges = TRUE)
data_info_2
```

## Таблица с абсолютными частотами групп крови у пациентов в двух разных группах
```{r}
#Таблица с абсолютными частотами групп крови у пациентов в двух разных группах
data_info_3 <- table(data_1$Группа, data_1$`Группа крови`) 
data_info_3
```

## Таблица с относительными частотами групп крови у пациентов в двух разных группах
```{r}
#Таблица с относительными частотами групп крови у пациентов в двух разных группах
data_info_4 <- prop.table(table(data_1$Группа, data_1$`Группа крови`) )
data_info_4
```


